utility_code: ameren
utility_name: "Ameren Illinois"
parent_company: "Ameren"
iso_id: miso
states: [IL]
data_source_type: arcgis_feature
requires_auth: false

# Ameren DG Hosting Capacity map (public ArcGIS Online)
service_url: "https://services.arcgis.com/TT9bIhJgpqQXKFnj/arcgis/rest/services/Ameren_DG_Hosting_Capacity/FeatureServer"
layer_index: 0
page_size: 2000
out_sr: 4326
capacity_unit: kw

url_discovery_method: static

field_map:
  FEEDER_ID: feeder_id_external
  FEEDER_NAME: feeder_name
  SUBSTATION: substation_name
  DG_HC_KW: hosting_capacity_mw
  EXISTING_DG_KW: installed_dg_mw
  QUEUED_DG_KW: queued_dg_mw
  REMAINING_KW: remaining_capacity_mw
  CONSTRAINT: constraining_metric
  VOLTAGE: voltage_kv
