utility_code: bge
utility_name: "Baltimore Gas & Electric"
parent_company: "Exelon"
iso_id: pjm
states: [MD]
data_source_type: arcgis_feature
requires_auth: false

service_url: "https://services3.arcgis.com/agWTKEK7X5K1Bx7o/arcgis/rest/services/BGE_Hosting_Capacity/FeatureServer"
layer_index: 38  # Quarter-mile grid-based polygons
page_size: 1000
out_sr: 4326
capacity_unit: kw

url_discovery_method: static

field_map:
  FEEDER_ID: feeder_id_external
  FEEDER_NAME: feeder_name
  SUBSTATION: substation_name
  HC_KW: hosting_capacity_mw
  EXISTING_DG_KW: installed_dg_mw
  QUEUED_DG_KW: queued_dg_mw
  LIMITING_FACTOR: constraining_metric
  VOLTAGE_KV: voltage_kv
