utility_code: dominion
utility_name: "Dominion Energy Virginia"
parent_company: "Dominion Energy"
iso_id: pjm
states: [VA, NC]
data_source_type: arcgis_feature
requires_auth: false

service_url: "https://services1.arcgis.com/JrAaMMksMPSYLfV0/arcgis/rest/services/Dominion_Hosting_Capacity/FeatureServer"
layer_index: 6  # Primary_HostingCapacity_Final
page_size: 2000
out_sr: 4326
capacity_unit: kw

url_discovery_method: static

field_map:
  FEEDER_ID: feeder_id_external
  FEEDER_NAME: feeder_name
  SUBSTATION_NAME: substation_name
  HOSTING_CAPACITY_KW: hosting_capacity_mw
  MIN_HC_KW: hosting_capacity_min_mw
  MAX_HC_KW: hosting_capacity_max_mw
  EXISTING_DG_KW: installed_dg_mw
  QUEUED_DG_KW: queued_dg_mw
  REMAINING_HC_KW: remaining_capacity_mw
  LIMITING_CRITERIA: constraining_metric
  VOLTAGE_KV: voltage_kv
  PHASE_CONFIG: phase_config
