utility_code: dpl
utility_name: "Delmarva Power & Light"
parent_company: "Exelon"
iso_id: pjm
states: [DE, MD]
data_source_type: arcgis_feature
requires_auth: false

service_url: "https://services3.arcgis.com/agWTKEK7X5K1Bx7o/arcgis/rest/services/PHI_Hosting_Capacity/FeatureServer"
layer_index: 2  # DPL
page_size: 3500
out_sr: 4326
capacity_unit: kw

url_discovery_method: static

field_map:
  FeederID: feeder_id_external
  Allowable_PV_kW: hosting_capacity_mw
  Strict_PV_kW: hosting_capacity_min_mw
  Max_PV_kW: hosting_capacity_max_mw
  Total_Active_Gen_kW: installed_dg_mw
  Total_Pending_Gen_kW: queued_dg_mw
  Voltage: voltage_kv
