utility_code: pge
utility_name: "Pacific Gas & Electric"
parent_company: null
iso_id: caiso
states: [CA]
data_source_type: arcgis_feature
requires_auth: false

service_url: "https://services2.arcgis.com/mJaJSax0KPHoCNB6/ArcGIS/rest/services/DRPComplianceRelProd/FeatureServer"
layer_index: 7  # ICAEstimatedCapacitySummary
page_size: 2000
out_sr: 4326
capacity_unit: kw

url_discovery_method: static

field_map:
  feederid: feeder_id_external
  csv_linesection: feeder_name
  loadica: hosting_capacity_mw
  loadapplications: installed_dg_mw
  plannedprojects: queued_dg_mw
  expectedcapacity: remaining_capacity_mw
