# Midcontinent ISO (MISO) configuration
iso_id: miso
iso_name: Midcontinent ISO
timezone: US/Eastern
gridstatus_class: MISO

peak_hours:
  start: 7
  end: 23

map_center: [40.0, -90.0]
map_zoom: 5

has_lmp_decomposition: true
has_node_level_pricing: true

rto_aggregates: []

states:
  - AR
  - IA
  - IL
  - IN
  - KY
  - LA
  - MI
  - MN
  - MO
  - MS
  - MT
  - ND
  - SD
  - TX
  - WI

# Zone names match gridstatus hub names from MISO DA LMP reports
zones:
  ARKANSAS.HUB:
    name: Arkansas Hub
    centroid_lat: 34.75
    centroid_lon: -92.30
    states: [AR]
  ILLINOIS.HUB:
    name: Illinois Hub
    centroid_lat: 39.00
    centroid_lon: -89.50
    states: [IL]
  INDIANA.HUB:
    name: Indiana Hub
    centroid_lat: 40.00
    centroid_lon: -86.25
    states: [IN]
  LOUISIANA.HUB:
    name: Louisiana Hub
    centroid_lat: 31.00
    centroid_lon: -92.00
    states: [LA]
  MICHIGAN.HUB:
    name: Michigan Hub
    centroid_lat: 43.00
    centroid_lon: -84.50
    states: [MI]
  MINN.HUB:
    name: Minnesota Hub
    centroid_lat: 46.00
    centroid_lon: -94.00
    states: [MN]
  MS.HUB:
    name: Mississippi Hub
    centroid_lat: 33.50
    centroid_lon: -89.50
    states: [MS]
  TEXAS.HUB:
    name: Texas Hub
    centroid_lat: 31.50
    centroid_lon: -97.00
    states: [TX]
